# Welcome to Jekyll!
#

# Site settings
title: DPA-Consortium Business Page
description: YOUR BEST DATA BUSINESS PARTNER!
owner: DPA-Consortium
first_published: 2021 # if migrating another site, the year of your first publish
email: ggnet2@ourcoms.kr
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
social:
  github: https://github.com/DPA-Consortium
  #facebook-official:
 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
